---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
