trigger:
  batch: true
  branches:
    include:
      - master
      - dev
      - release/*
      - feature/*
      - project/*

pr:
  - master
  - dev

pool:
  vmImage: ubuntu-latest

jobs:
- job: 'BuildAndPush'
  steps:
  - pwsh: |
      $branchtag=""
      echo "$(Build.SourceBranch)"
      if ("$(Build.SourceBranch)" -match ".*release/.*"){
        $branchtag=$( "$(Build.SourceBranch)" -replace "refs/heads/", "")
        $branchtag=$( $branchtag -replace "/", "--")
      }
      echo "branchtag: $branchtag"
      echo "##vso[task.setvariable variable=releaseTag;]$branchtag"

  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      containerRegistry: 'substrate-relayer'
      repository: 'gluwa/subscan-api'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest
        $(releaseTag)
