---
name: docker

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

permissions: read-all

jobs:
  make-sure-it-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build docker image
        run: |
          docker-compose build
          docker images
