---
name: release

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

permissions: read-all

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build docker image
        run: |
          docker-compose build
          docker images
